// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>

#include <Standard_Type.hxx>

#include <WfObjMesh_MeshTriangle.hxx>
#include <WfObjMesh_SequenceOfMeshTriangle.hxx>

 


IMPLEMENT_STANDARD_TYPE(WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle)


IMPLEMENT_DOWNCAST(WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle)


#define SeqItem Handle(WfObjMesh_MeshTriangle)
#define SeqItem_hxx <WfObjMesh_MeshTriangle.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshTriangle
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshTriangle.hxx>
#include <TCollection_SequenceNode.gxx>

