// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon.hxx>

#include <Standard_Type.hxx>

#include <WfObjMesh_MeshPolygon.hxx>
#include <WfObjMesh_SequenceOfMeshPolygon.hxx>

IMPLEMENT_STANDARD_TYPE(WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
STANDARD_TYPE(TCollection_SeqNode),
        STANDARD_TYPE(MMgt_TShared),
        STANDARD_TYPE(Standard_Transient),

        IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon)


IMPLEMENT_DOWNCAST(WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon)


#define SeqItem Handle(WfObjMesh_MeshPolygon)
#define SeqItem_hxx <WfObjMesh_MeshPolygon.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshPolygon
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshPolygon.hxx>
#include <TCollection_SequenceNode.gxx>

