// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WfObjMesh_SequenceOfMesh.hxx>

#include <Standard_NoSuchObject.hxx>
#include <Standard_OutOfRange.hxx>
#include <WfObjMesh_Mesh.hxx>
#include <WfObjMesh_SequenceNodeOfSequenceOfMesh.hxx>
 

#define SeqItem Handle(WfObjMesh_Mesh)
#define SeqItem_hxx <WfObjMesh_Mesh.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMesh.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMesh_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMesh
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMesh.hxx>
#include <TCollection_Sequence.gxx>

