// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WfObjMesh_SequenceOfMeshTriangle.hxx>

#include <Standard_NoSuchObject.hxx>
#include <Standard_OutOfRange.hxx>
#include <WfObjMesh_MeshTriangle.hxx>
#include <WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
 

#define SeqItem Handle(WfObjMesh_MeshTriangle)
#define SeqItem_hxx <WfObjMesh_MeshTriangle.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshTriangle
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshTriangle.hxx>
#include <TCollection_Sequence.gxx>

