// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WfObjMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>

#include <Standard_Type.hxx>

#include <WfObjMesh_MeshDomain.hxx>
#include <WfObjMesh_SequenceOfMeshDomain.hxx>

 


IMPLEMENT_STANDARD_TYPE(WfObjMesh_SequenceNodeOfSequenceOfMeshDomain)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(WfObjMesh_SequenceNodeOfSequenceOfMeshDomain)


IMPLEMENT_DOWNCAST(WfObjMesh_SequenceNodeOfSequenceOfMeshDomain,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(WfObjMesh_SequenceNodeOfSequenceOfMeshDomain)


#define SeqItem Handle(WfObjMesh_MeshDomain)
#define SeqItem_hxx <WfObjMesh_MeshDomain.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshDomain_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshDomain
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshDomain.hxx>
#include <TCollection_SequenceNode.gxx>

