// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <WfObjMesh_SequenceOfMeshPolygon.hxx>

#include <Standard_NoSuchObject.hxx>
#include <Standard_OutOfRange.hxx>
#include <WfObjMesh_MeshPolygon.hxx>
#include <WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon.hxx>


#define SeqItem Handle(WfObjMesh_MeshPolygon)
#define SeqItem_hxx <WfObjMesh_MeshPolygon.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshPolygon
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshPolygon.hxx>
#include <TCollection_Sequence.gxx>

