// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WfObjMesh_SequenceOfMeshDomain_HeaderFile
#define _WfObjMesh_SequenceOfMeshDomain_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <TCollection_BaseSequence.hxx>
#include <Handle_WfObjMesh_MeshDomain.hxx>
#include <Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#include <Standard_Integer.hxx>
class Standard_NoSuchObject;
class Standard_OutOfRange;
class WfObjMesh_MeshDomain;
class WfObjMesh_SequenceNodeOfSequenceOfMeshDomain;



class WfObjMesh_SequenceOfMeshDomain  : public TCollection_BaseSequence
{
public:

  DEFINE_STANDARD_ALLOC

  
    WfObjMesh_SequenceOfMeshDomain();
  
  Standard_EXPORT WfObjMesh_SequenceOfMeshDomain(const WfObjMesh_SequenceOfMeshDomain& Other);
  
  Standard_EXPORT   void Clear() ;
~WfObjMesh_SequenceOfMeshDomain()
{
  Clear();
}
  
  Standard_EXPORT  const  WfObjMesh_SequenceOfMeshDomain& Assign (const WfObjMesh_SequenceOfMeshDomain& Other) ;
 const  WfObjMesh_SequenceOfMeshDomain& operator = (const WfObjMesh_SequenceOfMeshDomain& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT   void Append (const Handle(WfObjMesh_MeshDomain)& T) ;
  
      void Append (WfObjMesh_SequenceOfMeshDomain& S) ;
  
  Standard_EXPORT   void Prepend (const Handle(WfObjMesh_MeshDomain)& T) ;
  
      void Prepend (WfObjMesh_SequenceOfMeshDomain& S) ;
  
      void InsertBefore (const Standard_Integer Index, const Handle(WfObjMesh_MeshDomain)& T) ;
  
      void InsertBefore (const Standard_Integer Index, WfObjMesh_SequenceOfMeshDomain& S) ;
  
  Standard_EXPORT   void InsertAfter (const Standard_Integer Index, const Handle(WfObjMesh_MeshDomain)& T) ;
  
      void InsertAfter (const Standard_Integer Index, WfObjMesh_SequenceOfMeshDomain& S) ;
  
  Standard_EXPORT  const  Handle(WfObjMesh_MeshDomain)& First()  const;
  
  Standard_EXPORT  const  Handle(WfObjMesh_MeshDomain)& Last()  const;
  
      void Split (const Standard_Integer Index, WfObjMesh_SequenceOfMeshDomain& Sub) ;
  
  Standard_EXPORT  const  Handle(WfObjMesh_MeshDomain)& Value (const Standard_Integer Index)  const;
 const  Handle(WfObjMesh_MeshDomain)& operator() (const Standard_Integer Index)  const
{
  return Value(Index);
}
  
  Standard_EXPORT   void SetValue (const Standard_Integer Index, const Handle(WfObjMesh_MeshDomain)& I) ;
  
  Standard_EXPORT   Handle(WfObjMesh_MeshDomain)& ChangeValue (const Standard_Integer Index) ;
  Handle(WfObjMesh_MeshDomain)& operator() (const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT   void Remove (const Standard_Integer Index) ;
  
  Standard_EXPORT   void Remove (const Standard_Integer FromIndex, const Standard_Integer ToIndex) ;




protected:





private:





};

#define SeqItem Handle(WfObjMesh_MeshDomain)
#define SeqItem_hxx <WfObjMesh_MeshDomain.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshDomain_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshDomain
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshDomain.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx




#endif // _WfObjMesh_SequenceOfMeshDomain_HeaderFile
