// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WfObjMesh_SequenceOfMeshPolygon_HeaderFile
#define _WfObjMesh_SequenceOfMeshPolygon_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <TCollection_BaseSequence.hxx>
#include <Handle_WfObjMesh_MeshPolygon.hxx>
#include <Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon.hxx>
#include <Standard_Integer.hxx>
class Standard_NoSuchObject;
class Standard_OutOfRange;
class WfObjMesh_MeshPolygon;
class WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon;

class WfObjMesh_SequenceOfMeshPolygon  : public TCollection_BaseSequence
{
public:

    DEFINE_STANDARD_ALLOC


    WfObjMesh_SequenceOfMeshPolygon();

    Standard_EXPORT WfObjMesh_SequenceOfMeshPolygon(const WfObjMesh_SequenceOfMeshPolygon& Other);

    Standard_EXPORT   void Clear() ;
    ~WfObjMesh_SequenceOfMeshPolygon()
    {
        Clear();
    }

    Standard_EXPORT  const  WfObjMesh_SequenceOfMeshPolygon& Assign (const WfObjMesh_SequenceOfMeshPolygon& Other) ;
    const  WfObjMesh_SequenceOfMeshPolygon& operator = (const WfObjMesh_SequenceOfMeshPolygon& Other)
    {
        return Assign(Other);
    }

    Standard_EXPORT   void Append (const Handle(WfObjMesh_MeshPolygon)& T) ;

    void Append (WfObjMesh_SequenceOfMeshPolygon& S) ;

    Standard_EXPORT   void Prepend (const Handle(WfObjMesh_MeshPolygon)& T) ;

    void Prepend (WfObjMesh_SequenceOfMeshPolygon& S) ;

    void InsertBefore (const Standard_Integer Index, const Handle(WfObjMesh_MeshPolygon)& T) ;

    void InsertBefore (const Standard_Integer Index, WfObjMesh_SequenceOfMeshPolygon& S) ;

    Standard_EXPORT   void InsertAfter (const Standard_Integer Index, const Handle(WfObjMesh_MeshPolygon)& T) ;

    void InsertAfter (const Standard_Integer Index, WfObjMesh_SequenceOfMeshPolygon& S) ;

    Standard_EXPORT  const  Handle(WfObjMesh_MeshPolygon)& First()  const;

    Standard_EXPORT  const  Handle(WfObjMesh_MeshPolygon)& Last()  const;

    void Split (const Standard_Integer Index, WfObjMesh_SequenceOfMeshPolygon& Sub) ;

    Standard_EXPORT  const  Handle(WfObjMesh_MeshPolygon)& Value (const Standard_Integer Index)  const;
    const  Handle(WfObjMesh_MeshPolygon)& operator() (const Standard_Integer Index)  const
    {
        return Value(Index);
    }

    Standard_EXPORT   void SetValue (const Standard_Integer Index, const Handle(WfObjMesh_MeshPolygon)& I) ;

    Standard_EXPORT   Handle(WfObjMesh_MeshPolygon)& ChangeValue (const Standard_Integer Index) ;
    Handle(WfObjMesh_MeshPolygon)& operator() (const Standard_Integer Index)
    {
        return ChangeValue(Index);
    }

    Standard_EXPORT   void Remove (const Standard_Integer Index) ;

    Standard_EXPORT   void Remove (const Standard_Integer FromIndex, const Standard_Integer ToIndex) ;
};

#define SeqItem Handle(WfObjMesh_MeshPolygon)
#define SeqItem_hxx <WfObjMesh_MeshPolygon.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshPolygon
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshPolygon.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx

#endif // _WfObjMesh_SequenceOfMeshPolygon_HeaderFile
