// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon_HeaderFile
#define _WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon.hxx>

#include <Handle_WfObjMesh_MeshPolygon.hxx>
#include <TCollection_SeqNode.hxx>
#include <TCollection_SeqNodePtr.hxx>
class WfObjMesh_MeshPolygon;
class WfObjMesh_SequenceOfMeshPolygon;

class WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon : public TCollection_SeqNode
{

public:
    WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon(const Handle(WfObjMesh_MeshPolygon)& I, const TCollection_SeqNodePtr& n, const TCollection_SeqNodePtr& p);

    Handle(WfObjMesh_MeshPolygon)& Value()  const;

    DEFINE_STANDARD_RTTI(WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon)

private:
    Handle(WfObjMesh_MeshPolygon) myValue;
};

#define SeqItem Handle(WfObjMesh_MeshPolygon)
#define SeqItem_hxx <WfObjMesh_MeshPolygon.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshPolygon
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshPolygon.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx

#endif // _WfObjMesh_SequenceNodeOfSequenceOfMeshPolygon_HeaderFile
