// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WfObjMesh_SequenceNodeOfSequenceOfMesh_HeaderFile
#define _WfObjMesh_SequenceNodeOfSequenceOfMesh_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_WfObjMesh_SequenceNodeOfSequenceOfMesh.hxx>

#include <Handle_WfObjMesh_Mesh.hxx>
#include <TCollection_SeqNode.hxx>
#include <TCollection_SeqNodePtr.hxx>
class WfObjMesh_Mesh;
class WfObjMesh_SequenceOfMesh;



class WfObjMesh_SequenceNodeOfSequenceOfMesh : public TCollection_SeqNode
{

public:

  
    WfObjMesh_SequenceNodeOfSequenceOfMesh(const Handle(WfObjMesh_Mesh)& I, const TCollection_SeqNodePtr& n, const TCollection_SeqNodePtr& p);
  
      Handle(WfObjMesh_Mesh)& Value()  const;




  DEFINE_STANDARD_RTTI(WfObjMesh_SequenceNodeOfSequenceOfMesh)

protected:




private: 


  Handle(WfObjMesh_Mesh) myValue;


};

#define SeqItem Handle(WfObjMesh_Mesh)
#define SeqItem_hxx <WfObjMesh_Mesh.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMesh.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMesh_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMesh
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMesh.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx




#endif // _WfObjMesh_SequenceNodeOfSequenceOfMesh_HeaderFile
