// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WfObjMesh_SequenceOfMeshTriangle_HeaderFile
#define _WfObjMesh_SequenceOfMeshTriangle_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <TCollection_BaseSequence.hxx>
#include <Handle_WfObjMesh_MeshTriangle.hxx>
#include <Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#include <Standard_Integer.hxx>
class Standard_NoSuchObject;
class Standard_OutOfRange;
class WfObjMesh_MeshTriangle;
class WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle;



class WfObjMesh_SequenceOfMeshTriangle  : public TCollection_BaseSequence
{
public:

  DEFINE_STANDARD_ALLOC

  
    WfObjMesh_SequenceOfMeshTriangle();
  
  Standard_EXPORT WfObjMesh_SequenceOfMeshTriangle(const WfObjMesh_SequenceOfMeshTriangle& Other);
  
  Standard_EXPORT   void Clear() ;
~WfObjMesh_SequenceOfMeshTriangle()
{
  Clear();
}
  
  Standard_EXPORT  const  WfObjMesh_SequenceOfMeshTriangle& Assign (const WfObjMesh_SequenceOfMeshTriangle& Other) ;
 const  WfObjMesh_SequenceOfMeshTriangle& operator = (const WfObjMesh_SequenceOfMeshTriangle& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT   void Append (const Handle(WfObjMesh_MeshTriangle)& T) ;
  
      void Append (WfObjMesh_SequenceOfMeshTriangle& S) ;
  
  Standard_EXPORT   void Prepend (const Handle(WfObjMesh_MeshTriangle)& T) ;
  
      void Prepend (WfObjMesh_SequenceOfMeshTriangle& S) ;
  
      void InsertBefore (const Standard_Integer Index, const Handle(WfObjMesh_MeshTriangle)& T) ;
  
      void InsertBefore (const Standard_Integer Index, WfObjMesh_SequenceOfMeshTriangle& S) ;
  
  Standard_EXPORT   void InsertAfter (const Standard_Integer Index, const Handle(WfObjMesh_MeshTriangle)& T) ;
  
      void InsertAfter (const Standard_Integer Index, WfObjMesh_SequenceOfMeshTriangle& S) ;
  
  Standard_EXPORT  const  Handle(WfObjMesh_MeshTriangle)& First()  const;
  
  Standard_EXPORT  const  Handle(WfObjMesh_MeshTriangle)& Last()  const;
  
      void Split (const Standard_Integer Index, WfObjMesh_SequenceOfMeshTriangle& Sub) ;
  
  Standard_EXPORT  const  Handle(WfObjMesh_MeshTriangle)& Value (const Standard_Integer Index)  const;
 const  Handle(WfObjMesh_MeshTriangle)& operator() (const Standard_Integer Index)  const
{
  return Value(Index);
}
  
  Standard_EXPORT   void SetValue (const Standard_Integer Index, const Handle(WfObjMesh_MeshTriangle)& I) ;
  
  Standard_EXPORT   Handle(WfObjMesh_MeshTriangle)& ChangeValue (const Standard_Integer Index) ;
  Handle(WfObjMesh_MeshTriangle)& operator() (const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT   void Remove (const Standard_Integer Index) ;
  
  Standard_EXPORT   void Remove (const Standard_Integer FromIndex, const Standard_Integer ToIndex) ;




protected:





private:





};

#define SeqItem Handle(WfObjMesh_MeshTriangle)
#define SeqItem_hxx <WfObjMesh_MeshTriangle.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshTriangle_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshTriangle
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshTriangle.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx

#endif // _WfObjMesh_SequenceOfMeshTriangle_HeaderFile
