// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WfObjMesh_SequenceOfMesh_HeaderFile
#define _WfObjMesh_SequenceOfMesh_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <TCollection_BaseSequence.hxx>
#include <Handle_WfObjMesh_Mesh.hxx>
#include <Handle_WfObjMesh_SequenceNodeOfSequenceOfMesh.hxx>
#include <Standard_Integer.hxx>
class Standard_NoSuchObject;
class Standard_OutOfRange;
class WfObjMesh_Mesh;
class WfObjMesh_SequenceNodeOfSequenceOfMesh;



class WfObjMesh_SequenceOfMesh  : public TCollection_BaseSequence
{
public:

  DEFINE_STANDARD_ALLOC

  
    WfObjMesh_SequenceOfMesh();
  
  Standard_EXPORT WfObjMesh_SequenceOfMesh(const WfObjMesh_SequenceOfMesh& Other);
  
  Standard_EXPORT   void Clear() ;
~WfObjMesh_SequenceOfMesh()
{
  Clear();
}
  
  Standard_EXPORT  const  WfObjMesh_SequenceOfMesh& Assign (const WfObjMesh_SequenceOfMesh& Other) ;
 const  WfObjMesh_SequenceOfMesh& operator = (const WfObjMesh_SequenceOfMesh& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT   void Append (const Handle(WfObjMesh_Mesh)& T) ;
  
      void Append (WfObjMesh_SequenceOfMesh& S) ;
  
  Standard_EXPORT   void Prepend (const Handle(WfObjMesh_Mesh)& T) ;
  
      void Prepend (WfObjMesh_SequenceOfMesh& S) ;
  
      void InsertBefore (const Standard_Integer Index, const Handle(WfObjMesh_Mesh)& T) ;
  
      void InsertBefore (const Standard_Integer Index, WfObjMesh_SequenceOfMesh& S) ;
  
  Standard_EXPORT   void InsertAfter (const Standard_Integer Index, const Handle(WfObjMesh_Mesh)& T) ;
  
      void InsertAfter (const Standard_Integer Index, WfObjMesh_SequenceOfMesh& S) ;
  
  Standard_EXPORT  const  Handle(WfObjMesh_Mesh)& First()  const;
  
  Standard_EXPORT  const  Handle(WfObjMesh_Mesh)& Last()  const;
  
      void Split (const Standard_Integer Index, WfObjMesh_SequenceOfMesh& Sub) ;
  
  Standard_EXPORT  const  Handle(WfObjMesh_Mesh)& Value (const Standard_Integer Index)  const;
 const  Handle(WfObjMesh_Mesh)& operator() (const Standard_Integer Index)  const
{
  return Value(Index);
}
  
  Standard_EXPORT   void SetValue (const Standard_Integer Index, const Handle(WfObjMesh_Mesh)& I) ;
  
  Standard_EXPORT   Handle(WfObjMesh_Mesh)& ChangeValue (const Standard_Integer Index) ;
  Handle(WfObjMesh_Mesh)& operator() (const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT   void Remove (const Standard_Integer Index) ;
  
  Standard_EXPORT   void Remove (const Standard_Integer FromIndex, const Standard_Integer ToIndex) ;




protected:





private:





};

#define SeqItem Handle(WfObjMesh_Mesh)
#define SeqItem_hxx <WfObjMesh_Mesh.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMesh.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMesh_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMesh
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMesh.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx




#endif // _WfObjMesh_SequenceOfMesh_HeaderFile
