// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _WfObjMesh_SequenceNodeOfSequenceOfMeshDomain_HeaderFile
#define _WfObjMesh_SequenceNodeOfSequenceOfMeshDomain_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>

#include <Handle_WfObjMesh_MeshDomain.hxx>
#include <TCollection_SeqNode.hxx>
#include <TCollection_SeqNodePtr.hxx>
class WfObjMesh_MeshDomain;
class WfObjMesh_SequenceOfMeshDomain;



class WfObjMesh_SequenceNodeOfSequenceOfMeshDomain : public TCollection_SeqNode
{

public:

  
    WfObjMesh_SequenceNodeOfSequenceOfMeshDomain(const Handle(WfObjMesh_MeshDomain)& I, const TCollection_SeqNodePtr& n, const TCollection_SeqNodePtr& p);
  
      Handle(WfObjMesh_MeshDomain)& Value()  const;




  DEFINE_STANDARD_RTTI(WfObjMesh_SequenceNodeOfSequenceOfMeshDomain)

protected:




private: 


  Handle(WfObjMesh_MeshDomain) myValue;


};

#define SeqItem Handle(WfObjMesh_MeshDomain)
#define SeqItem_hxx <WfObjMesh_MeshDomain.hxx>
#define TCollection_SequenceNode WfObjMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_hxx <WfObjMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#define Handle_TCollection_SequenceNode Handle_WfObjMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_Type_() WfObjMesh_SequenceNodeOfSequenceOfMeshDomain_Type_()
#define TCollection_Sequence WfObjMesh_SequenceOfMeshDomain
#define TCollection_Sequence_hxx <WfObjMesh_SequenceOfMeshDomain.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx




#endif // _WfObjMesh_SequenceNodeOfSequenceOfMeshDomain_HeaderFile
